package com.riversoforion.eyre.cmd

import com.github.ajalt.clikt.command.SuspendingCliktCommand
import com.github.ajalt.clikt.core.requireObject
import com.github.ajalt.clikt.parameters.arguments.argument
import com.github.ajalt.clikt.parameters.options.convert
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.options.required
import com.riversoforion.eyre.service.SecretStore
import kotlin.time.Duration
import kotlin.time.Instant

class Add : SuspendingCliktCommand() {

    val name by argument("name")
    val type by option("-t", "--type", help = "The type of the credential to add").required()
    val expires by option("-x", "--expires", help = "Expiration date of the new credential")
        .convert { Instant.parse(it) }
    val expiresIn by option("-i", "--expires-in", help = "Duration that the new credential is valid for")
        .convert { Duration.parse(it) }
    val id by option("--id", help = "The credential ID generated by the provider")
    val token by option("--token", help = "The API token")
    val client by option("--client", help = "The client ID")
    val secret by option("--secret", help = "The client secret")
    val fromJson by option("-j", "--from-json",
                           help = "JSON string with credential details (omit value to read from stdin)")
    // TODO custom parameters as a map, to create a CustomSecret

    val secretStore by requireObject<SecretStore>(Eyre.SECRET_STORE)

    override suspend fun run() { // Validate parameters
        // Build model object
        // Write to storage
        echo("Added credential: name='${name}' of type=${type}")
        echo("Additional details: expires=${expires}, id=${id}, token=${token}, client=${client}, secret=${secret}")
        echo("Secret store used: ${secretStore::class.simpleName}")
    }
}
