package com.riversoforion.eyre.cmd

import com.github.ajalt.clikt.command.SuspendingCliktCommand
import com.github.ajalt.clikt.parameters.arguments.argument
import com.github.ajalt.clikt.parameters.options.convert
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.options.required
import kotlin.time.Instant

class Add : SuspendingCliktCommand() {

    val name by argument("name")
    val type by option("-t", "--type", help = "The type of the credential to add").required()
    val expires by option("-x", "--expires", help = "Expiration date of the new credential")
        .convert { Instant.parse(it) }
    val expiresIn by option("-i", "--expires-in", help = "Duration that the new credential is valid for")
        .convert {  }
    val id by option("--id", help = "The credential ID generated by the provider")
    val token by option("--token", help = "The API token")
    val client = option("--client", help = "The client ID")
    val secret by option("--secret", help = "The client secret")

    override suspend fun run() {
        echo("Added credential: name='${name}' of type=${type}")
        echo("Additional details: expires=${expires}, id=${id}, token=${token}, client=${client}, secret=${secret}")
    }
}
